config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  resources :users, only: [:index, :edit, :show, :update] do
    member do
      get :follows, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end
  resources :games, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :game

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :genre, presence: true
  validates :detail, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :game

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed #自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower #自分をフォローしている人

  #ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  #ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  attachment :profile_image

  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    game = Game.find(params[:game_id])
    favorite = current_user.favorites.new(game_id: game.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    game = Game.find(params[:game_id])
    favorite = current_user.favorites.find_by(game_id: game.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
    @game = Game.new
    @user = current_user
  end

  def show
    @game = Game.find(params[:id])
    @user = @game.user
    @create = Game.new
    @post_comment = PostComment.new
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = current_user.id
    if @game.save
      redirect_to game_path(@game)
    else
      @user = current_user
      @games = Game.all
      render :index
    end
  end

  def edit
    @game = Game.find(params[:id])
    if @game.user == current_user
      render :edit
    else
      redirect_to games_path
    end
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:title, :genre, :detail)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    game = Game.find(params[:game_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.game_id = game.id
    comment.save
    redirect_to game_path(game)
  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to game_path(params[:game_id])
  end

  private
    def post_comment_params
      params.require(:post_comment).permit(:comment)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @game = Game.new
  end

  def show
    @user = User.find(params[:id])
    @game = Game.new
    @games = @user.games.all
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users= user.following_user.page(params[:page]).per(3).reverse_order
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<h2>投稿する</h2>
<%= form_with model: game, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "タイトル※必須", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, placeholder: "ジャンル※必須" , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :detail %>
    <%= f.text_area :detail, placeholder: "詳細※必須", class: "form-control", rows: "3"%>
  </div>
  <div class="form-group">
    <%= f.submit "投稿", class: "btn btn-success" %>
  </div>
<% end %>

app/views/games/_index.html.erb
<table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Genle</th>
            <th>Detail</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% games.each do |game| %>
          <tr>
            <td class="col-1">
              <%= link_to user_path(game.user) do %>
                <%= attachment_image_tag game.user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
              <% end %>
            </td>
            <td>
              <%= link_to game.title, game_path(game) %>
            </td>
            <td>
              <%= game.genre %>
            </td>
            <td class="text-truncate" style="max-width: 350px">
              <%= game.detail %>
            </td>
            <td>
              <% if game.favorited_by?(current_user) %>
                <p>
                  <%= link_to game_favorites_path(game), method: :delete, class: "text-danger" do %>
                    ♥<%= game.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to game_favorites_path(game), method: :post do %>
                    ♡<%= game.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <P class="far fa-comments"><%= game.post_comments.count %></P>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>編集画面</h2>
      <%= form_with model:@game, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control title", placeholder: "※必須" %>
      </div>
      <div class="form-group">
        <%= f.label :genre %>
        <%= f.text_field :genre, class: "form-control genre", placeholder: "※必須" %>
      </div>
      <div class="form-group">
        <%= f.label :detail %>
        <%= f.text_area :detail, class: "form-control detail", rows: "5" %>
      </div>
      <div class="btn-wrapper col-12 mx-auto">
        <div class="form-group row">
          <%= f.submit "変更", class: "btn btn-secondary btn-block" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "games/form", game: @game %>
    </div>
    <div class="col-md-9">
      <h2>Games</h2>
      <%= render "games/index", games: @games %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "games/form", game: @create %>
    </div>
    <div class="col-md-9">
      <h2>詳細</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@game.user) do %>
              <%= attachment_image_tag @game.user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %><br>
              <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= @game.title %>
          </td>
          <td>
            <%= @game.genre %>
          </td>
          <td>
            <% if @game.favorited_by?(current_user) %>
              <p>
                <%= link_to game_favorites_path(@game), method: :delete, class: "text-danger" do %>
                  ♥<%= @game.favorites.count %>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to game_favorites_path(@game), method: :post do %>
                  ♡<%= @game.favorites.count %>
                <% end %>
              </p>
            <% end %>
          </td>
          <td>
            <p>コメント：<%= @game.post_comments.count %></p>
          </td>
          <% if @game.user == current_user %>
          <td>
            <%= link_to "編集", edit_game_path(@game), class: "btn btn-success" %>
          </td>
          <td>
            <%= link_to "削除", game_path(@game), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
          </td>
          <% end %>
        </tr>
      </table>
      <div class="border-bottom">
      <%= @game.detail %>
      </div>
      <div class="mt-4">
        <% @game.post_comments.each do |post_comment| %>
        <div>
          <%= attachment_image_tag post_comment.user, :profile_image, :fill, 45, 45, fallback: "no_image.jpg" %><br>
          <%= post_comment.user.name %>
        </div>
          コメント：<%= post_comment.comment %>
          <% if post_comment.user == current_user %>
          <div>
            <%= link_to "削除", game_post_comment_path(post_comment.game, post_comment), method: :delete, class: "text-danger" %>
          </div>
          <% end %>
        <% end %>
        </div>
      <div class="form-group mt-4">
        <%= form_with(model:[@game, @post_comment], local:true) do |f| %>
          <%= f.text_area :comment, rows:"3", placeholder: "コメント" %>
          <div>
            <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-5">
  <div class="row">
    <h1 class="px-3 mx-auto">
      楽しんでください。
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="pl-3">ようこそ！
      <i class="fas fa-games"></i>
      <strong>Games</strong>
      へ!!</h1>
      <p class="pl-3">   このサイトでは各々好きなゲームを投稿・共有するサイトです。<br>
         コメントやいいねで評価していきましょう！
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign-in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign-up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/130f6a434c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "GAMES", root_path, class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
           aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto p-1">

              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light p-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light p-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "Games", games_path, class: "fas fa-gamepad nav-link text-light p-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light p-3" %>
              </li>

              <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "fas fa-home nav-link text-light p-3" %>
              </li>
              <li class="nav-item">
                <%= link_to 'About', about_path, class: 'fas fa-link nav-link text-light p-3' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'fas fa-user-plus nav-link text-light p-3' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log in', new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light p-3' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>後藤悠介が運営しています。</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
<th>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォローを外す", user_relationship_path(user.id), method: :delete, class: "btn-sm btn-danger fas fa-user-minus" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success fas fa-user-plus" %>
    <% end %>
  <% end %>
</th>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>
        フォロー：<%= user.following_user.count %>
      </th>
      <th>
        フォロワー：<%= user.follower_user.count %>
      </th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <span class="fas fa-user-cog"></span>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>編集画面</h2>
      <%= form_with model:@user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name", placeholder: "※必須" %>
      </div>
      <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "変更", class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "games/form", game: @game %>
    </div>
    <div class="col-md-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "60x60" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "詳細", user_path(user) %>
              </td>
              <td>
              <% if current_user != user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォローを外す", user_relationship_path(user.id, current_user), method: :delete, class: "btn-sm btn-danger fas fa-user-minus" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success fas fa-user-plus" %>
                <% end %>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "games/form", game: @game %>
    </div>
    <div class="col-md-9">
      <h2>Games</h2>
      <%= render "games/index", games: @games %>
    </div>
  </div>
</div>